theme: jekyll-theme-minimal
teaser: "https://ortimes.ir/wp-content/documents/header-git.png"
logo: "https://ortimes.ir/wp-content/documents/logo-git.png"
description: The GITpage for Creativity
image: "https://ortimes.ir/wp-content/documents/header-git.png"
name: Mohammad Namakshenas
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
url: https://ortimes.ir
